### ISSUE TITLE
font-face works error in version 1.9.6

### ISSUE THREAD

**Issue by assd12138** [zumerlab/snapdom#145]
### Describe it simply:
font-face works error in version 1.9.6

<img width="326" height="70" alt="Image" src="https://github.com/user-attachments/assets/5d52189a-a60d-4e38-89d7-c3dd7eaf04e7" />

### Quick demo to reproduce
https://stackblitz.com/edit/stackblitz-starters-628b2h1z?file=package.json

run
`yarn && yarn dev`

when change the version of snapdom to 1.9.5 and run this demo again,the font-face works fine

**Comment by tinchox5** [comment]
Thank you for opening  this issue and providing a demo

**Comment by tinchox5** [comment]
**Fixed!!** https://stackblitz.com/edit/stackblitz-starters-cy2hg8fh

Please confirm

**Comment by xiaoxiaoaobama** [comment]
我在vue3 vite6.0.3中复现上面这个案例，发现开发环境没问题，但是打包后生成环境有问题，mansalva字体未成功加载。

我使用的[snapdom](https://github.com/zumerlab/snapdom) 为1.9.7

**Comment by xiaoxiaoaobama** [comment]
@tinchox5

**Comment by tinchox5** [comment]
Hi @xiaoxiaoaobama, sorry I don't fully understand your message. Do you say that the bug is still present on vite production mode?

**Comment by xiaoxiaoaobama** [comment]
> Hi [@xiaoxiaoaobama](https://github.com/xiaoxiaoaobama), sorry I don't fully understand your message. Do you say that the bug is still present on vite production mode?

yes, the issue is still there in the production build.

vue3 vite6.0.3

**Comment by tinchox5** [comment]
I will see
