### ISSUE TITLE
embedFonts is not always applied

### ISSUE THREAD

**Issue by julientaq** [zumerlab/snapdom#253]
First, thank you for all your hard work.

i’m trying to use a TTF font variable with snapdom, but i can’t manage to make it works.

I made a demo repo. The idea is you can change the content of the block, and the styles with a small interface and output a downloadable images.

in this image, the top text is what i want,j the one in the bottom is what i can get. 

![Image](https://github.com/user-attachments/assets/69dc9360-4cfd-4082-bc93-94543759f2a2)

I m using the embedFonts.

i made a small repo with the project very quickly (it’s bad code, but good enough for bug fixes :)

https://github.com/julientaq/snapdom-test

tell me if i can do more to help looking at this, in the meantime, i’ll test other fonts and font styles.

**Comment by julientaq** [comment]
seems like this code pen still has an issue:

https://codepen.io/zircle/pen/VYLGOwp

**Comment by julientaq** [comment]
so it seems that it depends a lot on the complete loading of the font, some kind of race condition.

**Comment by tinchox5** [comment]
Thank you for your demo!! Which browser are you using? Safari?

**Comment by tinchox5** [comment]
ok, please try this update demo https://codepen.io/tinchox5/pen/myVEaEG that use latest dev version. I've tried on both good browsers and Safari ;) and is working ok.

I will check your repo now

**Comment by julientaq** [comment]
Thank you for the demo!

I’m using the latest chrome or the latest floorp / firefox and while this demo seems to work, my repo is not rendering the right font. 


--edit 

I tried with the exact font from the codepen locally, but it got stuck.

Is it possible that the issue comes from the server? 
or a missing font-weight / font-style?

or maybe some CORS happening without any log about it?

**Comment by tinchox5** [comment]
Yes maybe is a weight mismatch or something related. Let me some time for detect what's happening

**Comment by tinchox5** [comment]
The issue is taking me more time than I thought, I'm nbo sure if there is a problem with self  hosted fonts. I will update ASAP I got something

**Comment by julientaq** [comment]
ah :)
from an open source maintainer to an open source maintener, i do apreciate quite a lot that you’re looking into it.
thanks a lot.

**Comment by tinchox5** [comment]
I found the issue @julientaq. I takes me a lot because I didn't realize there is a mistake when you configured snapdom:

You did something like:
```js
 const result = await snapdom(element);
 const img = await result.toImg({embedFonts: true});

document.querySelector(".editor").appendChild(img);

```

But if you split the capture you need to set your options on first part, not in the exporter 
```js
const result = await snapdom(element, {embedFonts: true});
 const img = await result.toImg();

document.querySelector(".editor").appendChild(img);

```

Or do just in one line: 

```js
 const img = await snapdom.toImg(element, {embedFonts: true});
 document.querySelector(".editor").appendChild(img);
```

Thanks to your issue I detected a new bug when using `toImg()` exporter (its name should to toSvg() BTW), when `scale` is 1 it will expand to container size, that is not expected. Until I fixed you can use `scale`: 1.01 or 0.99. Or use anohter format like toPng()

**Comment by julientaq** [comment]
i’m officially a dumb idiot (again).

it totally makes sense.

thank you again.

**Comment by tinchox5** [comment]
On the contrary, I believe the api may lead to confusion. I will try to document it better or even modify it.

Thank you!

**Comment by julientaq** [comment]
I’m sorry but there may be more to it than what we got here.

i did try your one liner, but the font is still not there.

(dang i’m so sorry to write this).

i’ll have a proper look at it tomorrow morning as i dont want to let you do all the work. :D

**Comment by tinchox5** [comment]
No problem :)

**Comment by tinchox5** [comment]
Here it is my simplified demo using embeded snapdom dev version [demo.zip](https://github.com/user-attachments/files/22644494/demo.zip)

**Comment by julientaq** [comment]
so it’s interesting.

If the font is defined in the index.html

```
   @font-face {
        font-family: truculenta;
        src: url(./fonts/truculenta-variablefont.ttf) format("truetype");
        font-weight: 100 900;
        font-style: normal;
      }
      .balloon {
        font-family: "truculenta";
        font-synthesis: none;
      }
```

things work fine

if i set the font in the 

/css/modules/fonts.css

with 

```
@font-face {
  font-family: truculenta;
  src: url(../../fonts/truculenta-variablefont.ttf) format("truetype");
  font-weight: 100 900;
  font-style: normal;
}
```

then i loose the font.


so i did move the css:

/css/fonts 

```css
/*so this works. it’s intereting*/
@font-face {
  font-family: truculenta;
  src: url("../fonts/truculenta-variablefont.ttf") format("truetype");
  font-weight: 100 900;
  font-style: normal;
}
```

works fine.

so i did dig more and found out that if the font-face was inside a nested import, then it was lost. as if it was struggling with the font location.

but https://github.com/zumerlab/snapdom/blob/6ae2f9ad384d05ab41d91ffb6c3d5021d5e9e255/src/modules/fonts.js#L350 is having the exact location of the file. Which means that there is something else going on.

i need to finish the project i’m on, and i’ll get back to this.

thanks again for the support! i’ll be around.

**Comment by tinchox5** [comment]
Great, maybe it's related to how snapdom manages the relative paths. I will take a look

**Comment by tinchox5** [comment]
Done! I fixed and tested with your demo. I will release it with next stable version maybe tomorrow. In the meantime I updated the dev branch so you may compile your own version to test your real code. See Readme

**Comment by julientaq** [comment]
wow, that’s not a small commit.

thank you for all the work, it’s pretty neat.

**Comment by tinchox5** [comment]
jaja, mostly format and comments that I will stripe on the stable version

**Comment by tinchox5** [comment]
@julientaq I will modify the relative path detection a bit, because right now It make slow the capture especially on complex elements.

**Comment by julientaq** [comment]
Thank you for notifying me!

**Comment by akongG** [comment]
> const result = await snapdom(element, {embedFonts: true});
>  const img = await result.toImg();
> 
> document.querySelector(".editor").appendChild(img);
> 
This is solution
